// export { default as interestButton } from './interestButton';
export { default as Modal } from './modal/index';
// export { default as PhotoInput } from './photoInput';
export { Button } from './button/button';
export { ButtonLink } from './button/buttonLink';
export * from './input/input';
export { InputPhoto } from './input/inputPhoto';
export { InputCheckbox } from './input/inputCheckbox';
export { TextArea } from './input/textArea';
export { default as Carousel } from './carousel/index'; 