export const persons = [
    {
        id: 1,
        name: 'John Doe',
        age: 20,
        description: 'Я активный спортсмен. Обожаю бегать и играть в футбол.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?man',
    },
    {
        id: 2,
        name: 'Jane Doe',
        age: 21,
        description: 'Я люблю заниматься йогой и плаванием, чтобы поддерживать свою форму и здоровье.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?woman',
    },
    {
        id: 3,
        name: 'Alice',
        age: 22,
        description: 'Профессиональный спортсмен в теннисе и гольфе, постоянно стремлюсь к новым достижениям.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?woman',
    },
    {
        id: 4,
        name: 'Bob',
        age: 23,
        description: 'Я люблю заниматься фитнесом и кроссфитом для поддержания моей физической формы и здоровья.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?man',
    },
    {
        id: 5,
        name: 'Charlie',
        age: 24,
        description: 'Я поклонник экстремальных видов спорта, таких как скалолазание и парашютизм. Ищу новые ощущения и приключения.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?man',
    },
    {
        id: 6,
        name: 'David',
        age: 25,
        description: 'Я люблю участвовать в марафонах и триатлонах, чтобы испытать свою выносливость и преодолеть себя.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?man',
    },
    {
        id: 7,
        name: 'Eve',
        age: 26,
        description: 'Я профессиональный сноубордист, страстно люблю горные склоны и снежные вершины.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?landscape',
    },
    {
        id: 8,
        name: 'Frank',
        age: 27,
        description: 'Я люблю серфинг и вейкбординг, ищу новые волны и приключения на воде.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?ocean',
    },
    {
        id: 9,
        name: 'Grace',
        age: 28,
        description: 'Я фанат хайкинга и альпинизма, исследую горные хребты и ущелья в поисках новых впечатлений.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?moutain',
    },
    {
        id: 10,
        name: 'Hank',
        age: 29,
        description: 'Я люблю заниматься каякингом и парапланеризмом, ищу новые приключения на воде и в воздухе.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?forest',
    },
    {
        id: 11,
        name: 'Ivy',
        age: 30,
        description: 'Я страстно занимаюсь спортом и мечтаю принять участие в бодибилдинг-соревнованиях.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?sky',
    },
    {
        id: 12,
        name: 'Jack',
        age: 31,
        description: 'Я профессиональный скалолаз и альпинист, ищу новые вызовы и покоряю высоты.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?landscape',
    },
    {
        id: 13,
        name: 'Kathy',
        age: 32,
        description: 'Я люблю бегать марафоны и заниматься велоспортом, постоянно совершенствую свои результаты.',
        imageUrl: 'https://source.unsplash.com/random/1000x1000/?ocean',
    },
];
