name: Frontend CI

on:
  push:
    branches:
      - main
      - roflan-payments

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run lint

    - name: Build project
      run: npm run build
    
    - name: Print current directory
      run: pwd

    - name: List files in current directory
      run: ls -la

    - name: Deploy with Docker Compose
      run: |
        docker-compose up -d --build