name: Frontend CI

on:
  push:
    branches:
      - main
      - roflan-payments

env:
    DEPLOY_PATH: /var/www/app
    # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
    BUILD_SCRIPT: npm run build
    BUILD_SCRIPT_OUTPUT: dist

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Делаем checkout текущей ветки
            - uses: actions/checkout@v2
            # Устанавливаем Node.JS для сборки приложения
            - uses: actions/setup-node@v1
              with:
                node-version: '20'
            # Записываем в переменные окружения имя текущей ветки
            # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
            - name: Get branch name
              shell: bash
              run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g')"
                          # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
            - name: Get branch name
              shell: bash
              run: echo ${{env.BRANCH_NAME}}
            # Устанавливаем зависимости для сборки
            - name: Install Dependencies
              run: npm i
            # Делаем тесты
            - name: Run tests
              run: npm run lint        
            # Собираем приложение
            - name: Build Appliction
              run: $BUILD_SCRIPT
            - name: deploy
              uses: garygrossgarten/github-action-ssh@release
              with:
                host: ${{ secrets.DEPLOY_SERVER_HOST }}
                username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
                privateKey: ${{ secrets.DEPLOY_SERVER_KEY}}
                command: cd ~/project/client && git checkout ${{env.BRANCH_NAME}} && git pull && cd .. && docker compose up -d --build && docker system prune -a